<script src="https://cdn.bootcdn.net/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<link rel="stylesheet" href="/lib/sponsor-page/style.css">
<script src="/lib/sponsor-page/script.js"></script>
<div id="op">
<div id="DonateText" class="tr3">Sponsor</div>
<ul id="donateBox" class="list pos-f tr3">
<li id="AliPay">AliPay</li>
<li id="WeChat">WeChat</li>
<li id="QQPayOR">QQPayOR</li>
</ul>
<div id="QRBox" class="pos-f left-100">
<div id="MainBox">
</div></div>